---
kind: Service
apiVersion: v1
metadata:
  name: dvwa
  namespace: dvwa
  labels:
    app: dvwa
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  selector:
    app: dvwa
  type: NodePort
