---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: metasploit
  labels:
    app: postgres
    service: database
spec:
  ports:
  - name: http
    protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    app: postgres
    service: database
  type: ClusterIP
