---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: postgres
  namespace: metasploit
  labels:
    app: postgres
    service: database
spec:
  serviceName: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        service: database
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - name: http
          containerPort: 5432
        env:
        - name: PGDATA
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: data_dir
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: db_name
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: db_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: db_pass
        livenessProbe:
          exec:
            command:
              - pg_isready
          initialDelaySeconds: 1
          timeoutSeconds: 5
        # readinessProbe:
        #   exec:
        #     command:
        #       - '[ "$(pg_isready --username=gogs)" == "/var/run/postgresql:5432 - accepting connections" ] || exit 1'
        #   initialDelaySeconds: 1
        #   timeoutSeconds: 5
        resources:
          requests:
            cpu: "0.01"
