---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: dvwa
  labels:
    app: mysql
    service: database
spec:
  ports:
  - name: http
    protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
    service: database
  type: ClusterIP
